export { default as Feature } from './feature/Feature'
export { default as Navbar} from './navbar/Navbar'
export { default as CTA } from './cta/CTA'
export { default as Home } from './home/Home'
export { default as GetStarted } from './getstarted/GetStarted'
export { default as LearnMore } from './learnmore/LearnMore'